name: CI Pipeline

on: [push]

permissions:
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['21.6']

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Prettier Check
      run: npm run format:check 
    - name: ESLint
      run: npm run lint
    - name: Run Tests
      run: npm run test
    - run: npm run build --if-present
