name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['21.6']

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Prettier Check
      run: npm run format:check # Überprüfen Sie den Code-Stil mit Prettier
    - name: ESLint
      run: npm run lint # Führen Sie ESLint aus
    - name: Run Tests
      run: npm test
